blueprint:    
  name: air_conditioning_remote_change
  description: "Cambia temperatura condizionatore con telecomando"
  domain: automation
  source_url: https://github.com/giannisigalotti/HomeAssistant/blob/main/blueprints/air-conditioning-remote_change.yaml
  input:
    climate:
      name: Climatizzatore da attivare
      selector: 
        entity: 
          domain: climate
    remote:
      name: Telecomando di attivazione
      selector: 
        entity: 
          domain: remote   
    device: 
      name: Device associato al telecomando
      selector: 
        text: 
triggers:
  - entity_id: !input climate 
    attribute: temperature
    id: temp
    trigger: state
  - trigger: state
    entity_id: !input climate 
    attribute: hvac_action
variables:
    climatename: !input climate
conditions:
  - condition: template
    value_template: "{{ state_attr(climatename,'hvac_action') == 'cooling' }}"
actions:
  - variables:
      int: "{{ trigger.to_state.attributes.temperature | int }}"
  - action: script.turn_on
    entity_id: script.air_conditioning_broadlink_activation
    target:
      entity_id: script.air_conditioning_broadlink_activation
    data:
      variables:
        command: temperature
        temperature: "{{ int }}"
        remote: !input remote 
        device: !input device
mode: single
